---
language: python
python: "3.8"
cache: pip

# Use the new container infrastructure
sudo: required

# Enable the docker service
services:
  - docker

env:
  matrix:
    - ANSIBLE=2.9
    - ANSIBLE=2.10

# Install tox
install:
  - pip3 install tox-travis git-semver

# Execute tests
script:
  - tox

# Update Changelog and create a release (only from master branch)
deploy:
  provider: script
  skip_cleanup: true
  script: .travis/releaser.sh
  on:
    branch: master
branches:
  only:
    - master

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
