---

scenario:
  name: alternative

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: minio-centos-latest
    image: paulfantom/centos-molecule:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: minio-fedora-latest
    image: paulfantom/fedora-molecule:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: minio-debian-latest
    image: paulfantom/debian-molecule:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: minio-ubuntu-latest
    image: paulfantom/ubuntu-molecule:latest
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    diff: True
    v: True
  playbooks:
    create: ../resources/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/destroy.yml

lint:
  name: yamllint

verifier:
  name: testinfra
  options:
    vvv: True
  additional_files_or_dirs:
    - ../resources/tests/
  lint:
    name: flake8
